### ISSUE TITLE
Add an adjustable skill level (ELO for example) that works  

### ISSUE THREAD

**Issue by Zixer1** [py-stockfish/stockfish#27]
When using stockfish to implementent it to your chess game, if you currently want to have an adjustable skill level it doesnt really work, the best you can do is change the depth and reaction time but the "skill_level" doenst actually do much, what would be nice is a "set_elo" object that sets the bots elo to anything from 100 to 3900 and actually works

**Comment by kieferro** [comment]
The skill_level should actually already lead to the engine being better or worse. This means that it reaches a significantly lower depth at a lower skill level than at a high skill level. (If this doesn't work, then it's a bug and we will be happily fix it if you describe in more detail the case in which it occurs).
There is also already the [function to set an Elo value between 1320 and 3190](https://github.com/py-stockfish/stockfish#set-the-engines-elo-rating-ignoring-skill-level). This should work the same way as the skill level. We are also happy to fix bugs with this if necessary.

**Comment by johndoknjas** [comment]
Hi @Zixer1, for skill_level and elo, expected behaviour should be sometimes getting the best move, and sometimes getting a lower ranked move. Stockfish decides this randomly, where the extent of the randomness is related to the strength you set. Is this similar to what you're getting?

**Comment by Zixer1** [comment]
Hi, yes, that is what I'm getting, but what would be interesting is if we could have Stockfish play at a specific Elo constantly. So, for example, if I put a very low skill level, it would play very badly.

**Comment by johndoknjas** [comment]
@Zixer1 Unfortunately that's just Stockfish's behaviour, so it's probably beyond the scope of this python wrapper. I'm not aware of Stockfish having an option to consistently never play the top move. Although it does use some algorithm behind the scenes for the move selection, in order to approximate the elo you've set Stockfish to. I'm not sure how it works, but I'd assume that at lower elos, worse moves have a higher probability of being played. The relevant source code is here: https://github.com/official-stockfish/Stockfish/blob/master/src/search.cpp#L93-L96

If you'd prefer to never choose the best move, maybe what you could do is call the get_top_moves function of the python wrapper. Then, you can choose a suboptimal move from that selection however you wish. Although if you wanted something like say the 15th top move, get_top_moves(15) would have Stockfish use 15 principal variations, so the search would take longer.
