### ISSUE TITLE
IndexError on MacOS (MacBook M2) [BUG]

### ISSUE THREAD

**Issue by nIKiTaaaaaaa-coder** [py-stockfish/stockfish#48]
Traceback (most recent call last):
  File "/Users/nsegrenev/Documents/Python Projects/console_ches.py", line 305, in <module>
    stockfish = Stockfish(path="/Applications/Stockfish.app/Contents/MacOS/stockfish-x86-64-vnni256")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/stockfish/models.py", line 58, in __init__
    self._read_line().split(" ")[1].split(".")[0].replace("-", "")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

How do I fix this?

**Comment by kieferro** [comment]
This is a bug concerning the version parsing and something similar has already been reported in #11 and fixed in #25.
Since we use different methods to detect the version I suspect that this problem has already been fixed.
But I would still be interested in how this problem occurs. Could you paste the output of the engine at startup (via command line) and the response after you use the `uci` command?

**Comment by nIKiTaaaaaaa-coder** [comment]
```nsegrenev@192 ~ % stockfish                                              
Stockfish 15.1 by the Stockfish developers (see AUTHORS file)
```

**Comment by nIKiTaaaaaaa-coder** [comment]
or should I run the binary of the stockfish app?
```
nsegrenev@192 MacOS % ./Stockfish
2023-06-30 09:47:15.737 Stockfish[10787:382138] Warning: Column selection is not supported in view-based table and outline views (<NSTableView: 0x121822e00>).
2023-06-30 09:47:15.759 Stockfish[10787:382138] Launching engine with path /Applications/Stockfish.app/Contents/MacOS/stockfish-arm64
2023-06-30 09:47:15.782 Stockfish[10787:382138] Started app
```

**Comment by nIKiTaaaaaaa-coder** [comment]
```
nsegrenev@192 MacOS % uci
zsh: command not found: uci
```
Should I install sci via homebrew?

**Comment by kieferro** [comment]
> or should I run the binary of the stockfish app?
> 
> ```
> nsegrenev@192 MacOS % ./Stockfish
> 2023-06-30 09:47:15.737 Stockfish[10787:382138] Warning: Column selection is not supported in view-based table and outline views (<NSTableView: 0x121822e00>).
> 2023-06-30 09:47:15.759 Stockfish[10787:382138] Launching engine with path /Applications/Stockfish.app/Contents/MacOS/stockfish-arm64
> 2023-06-30 09:47:15.782 Stockfish[10787:382138] Started app
> ```

Was that the version you were using? That would explain it, because the parser then tries to read the version number from the warning message, which of course can't work.




> Should I install sci via homebrew?

I'm sorry if that wasn't clear: The `uci` command is for chess engines, not for the command line. So you would have to start the engine from the command line and just input uci to get some basic information about the engine.

**Comment by johndoknjas** [comment]
@nIKiTaaaaaaa-coder Building on what kieferro said, if you could do something like the following that would be good:
![image](https://github.com/py-stockfish/stockfish/assets/32089502/666b4d9b-b308-4bbd-89c9-05d861de2695)
Here I'm running Linux, but it should be similar on Mac. The 'stockfish-engine' is just the name of the stockfish executable I'm using myself. Once it loads, typing `uci` will get stockfish to output all that information.

Also, the version of the Python Stockfish library on PyPI was last updated in July 2022. The code in this repo is the updated version, but unfortunately we haven't been able to upload it on PyPI yet. You could try making a new `models.py` file in your project directory, copying [the code](https://github.com/py-stockfish/stockfish/blob/master/stockfish/models.py) into it, and then in your main file, doing `from models import Stockfish` instead of `from stockfish import Stockfish`. If things then run fine for you, this was likely a bug we patched within the last year.

**Comment by nIKiTaaaaaaa-coder** [comment]
how do I find the engine? I downloaded the app and I have these:
<img width="304" alt="Снимок экрана 2023-07-03 в 18 31 55" src="https://github.com/py-stockfish/stockfish/assets/70052563/b6889641-a33e-457c-9c83-0f5163cd4fac">

**Comment by nIKiTaaaaaaa-coder** [comment]
I am sorry, I just set the incorrect path for the engine, I had to choose the path from homebrew, not from the app.
